apiVersion: v1
kind: Pod
metadata:
  name: maestro-client
spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: nodetype
                operator: In
                values:
                  - maestroperf
  containers:
    - name: idle
      image: centos:7
      command:
        - /bin/bash
        - -c
        - sleep 1800
    - name: client
      image: maestroperf/maestro-client:1.5.0-SNAPSHOT
      command:
        - /bin/bash
        - -c
        - /opt/maestro/maestro-cli/bin/maestro-cli maestro -m ${MAESTRO_BROKER} -c unassign
      env:
        - name: MAESTRO_BROKER
          value: mqtt://broker