apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-reports
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reports
      app: maestro
  template:
    metadata:
      labels:
        component: reports
        app: maestro
    spec:
#      strategy:
#        type: Recreate
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: maestro-node-role
                    operator: In
                    values:
                      - infra
      containers:
        - name: maestro-reports
          image: maestroperf/maestro-reports:edge
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/live
              port: 6500
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 20
            failureThreshold: 3
          env:
            - name: MAESTRO_BROKER
              value: mqtt://broker
          ports:
            - name: http
              containerPort: 6500
          volumeMounts:
            - mountPath: /maestro
              name: reports-data
      volumes:
        - name: reports-data
          persistentVolumeClaim:
            claimName: reports-data
