#!/bin/bash
#   Copyright 2017 Otavio Rodolfo Piske
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

localdir=`dirname $0`
installdir=`dirname ${localdir}`

if [ "$installdir" = "." ] ; then
	installdir=".."
fi

source "$installdir"/config/maestro-inspector-service.conf

RED="\e[0;31m"
GREEN="\e[0;32m"
RESET="\e[0m"

function esuccess() {
    echo -e "$GREEN OK$RESET"
}

function eerror() {
    echo -e "$RED failed$RESET ($@)"
}

function start() {
    echo -en "Starting the daemon: "
    nohup "$installdir"/bin/maestro-inspector -m "$MAESTRO_BROKER" -i "$MAESTRO_INSPECTOR_CLASS" -l "$MAESTRO_LOG_DIR" $@ > /dev/null 2> /dev/null &
    if [ $? -ne 0 ] ; then
        eerror "failed to daemonize the Maestro inspector"
        exit 1
    fi

    sleep 2s
    proc_count=0
    for pid in $(ps -ef | grep -i maestro-inspector | grep java | grep -v inspector-service | grep -v grep | awk ' { print $2 } ') ; do
        if [ $proc_count -eq 0 ] ; then
            esuccess
        fi
        echo -e "Maestro inspector started:$GREEN $pid $RESET"
    done

    if [ $proc_count -eq 0 ] ; then
        eerror "Maestro inspector did not start successfully"
    fi
}

function stop() {
    for pid in $(ps -ef | grep -i maestro-inspector | grep -v service | grep -i "$MAESTRO_WORKER_ROLE" | grep -v grep | awk ' { print $2 } ') ; do
        echo "Killing maestro-inspector $pid"
        kill -TERM ${pid}
    done
}

function restart() {
    stop
    start

}

function printHelp() {
    echo "Usage: $0 [start|stop|restart]"
}


if [[ -z "$1" ]] ; then
    printHelp
    exit 1
fi


case "$1" in
	start)
		start $2 $3
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		printHelp
		RETVAL=2
esac