#!/bin/bash
#   Copyright 2017 Otavio Rodolfo Piske
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

localdir=`dirname $0`
installdir=`dirname ${localdir}`

if [ "$installdir" = "." ] ; then
	installdir=".."
fi

source "$installdir"/config/maestro-agent-service.conf

function start() {
    if [[ "$MAESTRO_WORKER_ROLE" == "sender" ]] ; then
        export MAESTRO_WORKER="$MAESTRO_SENDER_WORKER"
    else
        export MAESTRO_WORKER="$MAESTRO_RECEIVER_WORKER"
    fi

    if [[ -z "$MAESTRO_LOCAL_HOSTNAME" ]] ; then
        MAESTRO_LOCAL_HOSTNAME=$(hostname -f)
    fi

    nohup "$installdir"/bin/maestro-worker -m "$MAESTRO_BROKER" -w "$MAESTRO_WORKER" -l "$MAESTRO_LOG_DIR" -r "$MAESTRO_WORKER_ROLE" -H "$MAESTRO_LOCAL_HOSTNAME" $@ > /dev/null 2> /dev/null &
    sleep 2s
    for pid in $(ps -ef | grep -i maestro-worker | grep java | grep -v worker-service | grep -i "$MAESTRO_WORKER_ROLE"  | grep -v grep | awk ' { print $2 } ') ; do
        echo "Maestro agent started $pid"
    done
}

function stop() {
    for pid in $(ps -ef | grep -i maestro-worker | grep -v service | grep -i "$MAESTRO_WORKER_ROLE" | grep -v grep | awk ' { print $2 } ') ; do
        echo "Killing maestro-agent $pid"
        kill -TERM ${pid}
    done
}

function restart() {
    stop
    start

}

function printHelp() {
    echo "Usage: $0 [start|stop|restart]"
}


if [[ -z "$1" ]] ; then
    printHelp
    exit 1
fi


case "$1" in
	start)
		start $2 $3
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		printHelp
		RETVAL=2
esac