apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      component: inspector
      app: maestro
  template:
    metadata:
      labels:
        component: inspector
        app: maestro
    spec:
#      strategy:
#        type: Recreate
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: maestro-node-role
                    operator: In
                    values:
                      - infra
      containers:
        - name: inspector
          image: maestroperf/maestro-inspector:edge
          imagePullPolicy: Always
          env:
            - name: MAESTRO_BROKER
              value: mqtt://broker
          volumeMounts:
            - mountPath: /maestro
              name: data
      volumes:
        - name: data
          emptyDir: {}