#!/bin/bash
#   Copyright 2017 Otavio Rodolfo Piske
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


cygwin=false;
darwin=false;
mingw=false;

# OS specific support.  $var _must_ be set to either true or false.
case "`uname`" in
  CYGWIN*) cygwin=true ;;
  MINGW*) mingw=true;;
  Darwin*) darwin=true
           if [ -z "$JAVA_VERSION" ] ; then
             JAVA_VERSION="CurrentJDK"
           fi
           if [ -z "$JAVA_HOME" ] ; then
             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
           fi
           ;;
esac

# For Cygwin, ensure paths are in UNIX format before anything is touched
if ${cygwin} ; then
  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
fi

localdir=`dirname $0`
installdir=`dirname ${localdir}`

if [ "$installdir" = "." ] ; then
	installdir=".."
fi

MAESTRO_CLASSPATH=""

for jarfile in "$installdir"/bin/*.jar ; do
    if [ -z "$MAESTRO_CLASSPATH" ] ; then
        export MAESTRO_CLASSPATH="$jarfile"
    else
        export MAESTRO_CLASSPATH="$MAESTRO_CLASSPATH:$jarfile"
    fi
done


for jarfile in "$installdir"/lib/*.jar ; do
    if [ -z "$MAESTRO_CLASSPATH" ] ; then
        export MAESTRO_CLASSPATH="$jarfile"
    else
        export MAESTRO_CLASSPATH="$MAESTRO_CLASSPATH:$jarfile"
    fi
done

for jarfile in "$installdir"/lib/ext/*.jar ; do
    if [ -z "$MAESTRO_CLASSPATH" ] ; then
        export MAESTRO_CLASSPATH="$jarfile"
    else
        export MAESTRO_CLASSPATH="$MAESTRO_CLASSPATH:$jarfile"
    fi
done

mainclass=org.maestro.cli.main.Main

java -classpath ${MAESTRO_CLASSPATH} -Dorg.maestro.home="$installdir" -Djava.awt.headless=true "$mainclass" $@
